// pages/TrackCasePageStyles.js
import { StyleSheet } from 'react-native';
import {
  PRIMARY_GOLD,
  PRIMARY_BROWN,
  MUTED_OLIVE,
  CHARCOAL,
} from 'utils/constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: CHARCOAL,
    letterSpacing: -0.3,
  },
  headerSpacer: {
    width: 40,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: MUTED_OLIVE,
    fontWeight: '500',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: CHARCOAL,
    marginTop: 24,
    marginBottom: 12,
  },
  emptyText: {
    fontSize: 15,
    color: MUTED_OLIVE,
    textAlign: 'center',
    lineHeight: 22,
  },
  caseListContainer: {
    flex: 1,
    padding: 20,
  },
  caseCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 18,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0EDE3',
  },
  caseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  caseTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    color: CHARCOAL,
    marginRight: 12,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  caseType: {
    fontSize: 13,
    color: PRIMARY_BROWN,
    fontWeight: '600',
    marginBottom: 6,
  },
  caseDescription: {
    fontSize: 14,
    color: MUTED_OLIVE,
    lineHeight: 20,
    marginBottom: 12,
  },
  caseCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE3',
  },
  caseDate: {
    fontSize: 12,
    color: MUTED_OLIVE,
    fontWeight: '500',
  },
  detailsContainer: {
    flex: 1,
    padding: 20,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: CHARCOAL,
    fontWeight: '600',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  detailsTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: CHARCOAL,
    marginBottom: 8,
    letterSpacing: -0.3,
  },
  detailsType: {
    fontSize: 14,
    color: PRIMARY_BROWN,
    fontWeight: '600',
    marginBottom: 12,
  },
  detailsDescription: {
    fontSize: 15,
    color: MUTED_OLIVE,
    lineHeight: 22,
    marginBottom: 16,
  },
  detailsInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  detailsInfoText: {
    fontSize: 14,
    color: MUTED_OLIVE,
    fontWeight: '500',
  },
  attorneyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF9F0',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    gap: 12,
    borderLeftWidth: 3,
    borderLeftColor: PRIMARY_GOLD,
  },
  attorneyInfo: {
    flex: 1,
  },
  attorneyName: {
    fontSize: 16,
    fontWeight: '700',
    color: CHARCOAL,
    marginBottom: 4,
  },
  attorneySpec: {
    fontSize: 13,
    color: MUTED_OLIVE,
    fontWeight: '500',
  },
  trackerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 20,
  },
  trackerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: CHARCOAL,
    marginBottom: 20,
    letterSpacing: -0.2,
  },
  progressContainer: {
    paddingLeft: 4,
  },
  progressStep: {
    flexDirection: 'row',
    marginBottom: 24,
  },
  progressStepLeft: {
    alignItems: 'center',
    marginRight: 16,
  },
  progressDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E0DDD5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  progressDotCompleted: {
    backgroundColor: '#5A8F5A',
  },
  progressDotCurrent: {
    backgroundColor: PRIMARY_BROWN,
    borderColor: PRIMARY_GOLD,
  },
  progressLine: {
    width: 3,
    flex: 1,
    backgroundColor: '#E0DDD5',
    marginVertical: 4,
  },
  progressLineCompleted: {
    backgroundColor: '#5A8F5A',
  },
  progressStepContent: {
    flex: 1,
    paddingTop: 4,
  },
  progressStepTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#A0A0A0',
    marginBottom: 4,
  },
  progressStepTitleCurrent: {
    color: PRIMARY_BROWN,
  },
  progressStepTitleUpcoming: {
    color: '#C0C0C0',
  },
  progressStepDescription: {
    fontSize: 13,
    color: MUTED_OLIVE,
    lineHeight: 19,
  },
});

export default styles;