// styles.js
import { StyleSheet } from 'react-native';
import {
  PRIMARY_GOLD,
  PRIMARY_BROWN,
  MUTED_OLIVE,
  THEMED_LIGHT_BG,
  CHARCOAL,
  ACCENT_TAN
} from 'utils/constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F0',
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 50,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logoPlaceholder: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: PRIMARY_GOLD,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PRIMARY_BROWN,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  logoImage: {
    width: 42,
    height: 42,
    borderRadius: 12,
    resizeMode: 'contain',
  },
  appName: {
    fontSize: 26,
    fontWeight: '700',
    color: PRIMARY_BROWN,
    marginLeft: 14,
    letterSpacing: -0.5,
  },
  headerLogoutButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: THEMED_LIGHT_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLogoutDisabled: {
    opacity: 0.4,
  },
  scrollView: {
    flex: 1,
  },
  welcomeSection: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 28,
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
  },
  welcomeText: {
    fontSize: 15,
    color: MUTED_OLIVE,
    marginBottom: 6,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  nameText: {
    fontSize: 32,
    fontWeight: '700',
    color: CHARCOAL,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  emailText: {
    fontSize: 14,
    color: MUTED_OLIVE,
    fontWeight: '400',
  },
  content: {
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  sectionHeader: {
    fontSize: 22,
    fontWeight: '700',
    color: CHARCOAL,
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    gap: 12,
  },
  statusCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 24,
    paddingHorizontal: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F0EDE3',
  },
  statusNumber: {
    fontSize: 40,
    fontWeight: '700',
    color: PRIMARY_BROWN,
    marginBottom: 8,
    letterSpacing: -1,
  },
  statusLabel: {
    fontSize: 12,
    color: MUTED_OLIVE,
    textAlign: 'center',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  buttonContainer: {
    gap: 14,
  },
  primaryButton: {
    backgroundColor: PRIMARY_BROWN,
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: PRIMARY_BROWN,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonDisabled: {
    backgroundColor: '#94a3b8',
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
    shadowOpacity: 0,
    elevation: 0,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  secondaryButton: {
    backgroundColor: PRIMARY_GOLD,
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: PRIMARY_GOLD,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  secondaryButtonText: {
    color: CHARCOAL,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  chatButton: {
    backgroundColor: ACCENT_TAN,
    borderRadius: 14,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: ACCENT_TAN,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  chatButtonDisabled: {
    backgroundColor: '#E0DDD5',
    shadowOpacity: 0,
    elevation: 0,
  },
  chatButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  chatButtonTextDisabled: {
    color: MUTED_OLIVE,
    fontWeight: '600',
  },
  disabledNote: {
    fontSize: 11,
    color: MUTED_OLIVE,
    marginTop: 6,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  loadingSection: {
    paddingVertical: 20,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
  },
  attorneySection: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    marginBottom: 16,
  },
  attorneyCard: {
    flexDirection: 'row',
    backgroundColor: '#F5EFE7',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8DCC8',
  },
  attorneyAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 2,
    borderColor: '#C5A572',
  },
  attorneyInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  attorneyName: {
    fontSize: 18,
    fontWeight: '700',
    color: PRIMARY_BROWN,
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  attorneyEmail: {
    fontSize: 13,
    color: MUTED_OLIVE,
    marginBottom: 2,
  },
  attorneyPhone: {
    fontSize: 13,
    color: MUTED_OLIVE,
    marginBottom: 2,
  },
  attorneySpec: {
    fontSize: 11,
    color: '#8B6F47',
    marginTop: 4,
    fontStyle: 'italic',
  },
  caseInfo: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    textAlign: 'center',
  },
});

export default styles;