/**
 * Signature Cryptography Utility
 * 
 * Provides:
 *  1. AES-256-GCM encryption/decryption — hides image data before Cloudinary upload
 *  2. SHA-256 hashing — creates a unique fingerprint of the original image
 *  3. RSA digital signing/verification — proves the hash was generated by this server
 *
 * Keys: RSA 2048-bit PKCS#1 pair in server/config/keys/
 * AES key: Derived from SIGNATURE_AES_SECRET env var via PBKDF2
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── Load RSA Keys ──
const KEYS_DIR = path.join(__dirname, '..', 'config', 'keys');
const PRIVATE_KEY = fs.readFileSync(path.join(KEYS_DIR, 'privateKey.pem'), 'utf8');
const PUBLIC_KEY = fs.readFileSync(path.join(KEYS_DIR, 'publicKey.pem'), 'utf8');

// ── AES-256-GCM Key Derivation ──
// Uses PBKDF2 to derive a stable 256-bit key from env secret + fixed salt
const AES_SECRET = process.env.SIGNATURE_AES_SECRET || 'sola-justreach-sig-default-secret-change-me';
const AES_SALT = 'sola-signature-salt-v1';
const AES_KEY = crypto.pbkdf2Sync(AES_SECRET, AES_SALT, 100000, 32, 'sha256');

/**
 * Compute SHA-256 hash of raw data (Buffer or string)
 * @param {Buffer|string} data 
 * @returns {string} hex-encoded hash
 */
export function hashSignature(data) {
  return crypto.createHash('sha256').update(data).digest('hex');
}

/**
 * RSA-sign a hash string using the server's private key
 * @param {string} hash — hex-encoded SHA-256 hash
 * @returns {string} base64-encoded RSA signature (proof)
 */
export function rsaSign(hash) {
  const sign = crypto.createSign('RSA-SHA256');
  sign.update(hash);
  sign.end();
  return sign.sign({ key: PRIVATE_KEY, padding: crypto.constants.RSA_PKCS1_PADDING }, 'base64');
}

/**
 * Verify an RSA signature against a hash using the server's public key
 * @param {string} hash — hex-encoded SHA-256 hash
 * @param {string} proof — base64-encoded RSA signature
 * @returns {boolean}
 */
export function rsaVerify(hash, proof) {
  try {
    const verify = crypto.createVerify('RSA-SHA256');
    verify.update(hash);
    verify.end();
    return verify.verify({ key: PUBLIC_KEY, padding: crypto.constants.RSA_PKCS1_PADDING }, proof, 'base64');
  } catch {
    return false;
  }
}

/**
 * AES-256-GCM encrypt a buffer
 * @param {Buffer} plainBuffer — raw image data
 * @returns {{ encrypted: string, iv: string, authTag: string }} — all base64
 */
export function aesEncrypt(plainBuffer) {
  const iv = crypto.randomBytes(12); // 96-bit IV for GCM
  const cipher = crypto.createCipheriv('aes-256-gcm', AES_KEY, iv);
  const encrypted = Buffer.concat([cipher.update(plainBuffer), cipher.final()]);
  const authTag = cipher.getAuthTag();

  return {
    encrypted: encrypted.toString('base64'),
    iv: iv.toString('base64'),
    authTag: authTag.toString('base64'),
  };
}

/**
 * AES-256-GCM decrypt back to a buffer
 * @param {string} encryptedB64 — base64 ciphertext
 * @param {string} ivB64 — base64 IV
 * @param {string} authTagB64 — base64 auth tag
 * @returns {Buffer} — decrypted raw image data
 */
export function aesDecrypt(encryptedB64, ivB64, authTagB64) {
  const decipher = crypto.createDecipheriv(
    'aes-256-gcm',
    AES_KEY,
    Buffer.from(ivB64, 'base64')
  );
  decipher.setAuthTag(Buffer.from(authTagB64, 'base64'));
  const decrypted = Buffer.concat([
    decipher.update(Buffer.from(encryptedB64, 'base64')),
    decipher.final(),
  ]);
  return decrypted;
}

/**
 * Full pipeline: encrypt image data + compute hash + RSA-sign
 * @param {Buffer} imageBuffer — raw PNG data
 * @returns {{ encrypted, iv, authTag, hash, proof }}
 */
export function encryptAndSign(imageBuffer) {
  const hash = hashSignature(imageBuffer);
  const proof = rsaSign(hash);
  const { encrypted, iv, authTag } = aesEncrypt(imageBuffer);
  return { encrypted, iv, authTag, hash, proof };
}

/**
 * Full pipeline: decrypt + verify integrity
 * @param {{ encrypted, iv, authTag, hash, proof }} record
 * @returns {{ verified: boolean, imageBuffer: Buffer|null }}
 */
export function decryptAndVerify(record) {
  const { encrypted, iv, authTag, hash, proof } = record;

  // Step 1: verify RSA proof
  const proofValid = rsaVerify(hash, proof);
  if (!proofValid) return { verified: false, imageBuffer: null, reason: 'RSA proof invalid' };

  // Step 2: decrypt
  let imageBuffer;
  try {
    imageBuffer = aesDecrypt(encrypted, iv, authTag);
  } catch (err) {
    return { verified: false, imageBuffer: null, reason: 'Decryption failed (tampered ciphertext)' };
  }

  // Step 3: re-hash decrypted data and compare
  const recomputedHash = hashSignature(imageBuffer);
  if (recomputedHash !== hash) {
    return { verified: false, imageBuffer: null, reason: 'Hash mismatch after decryption' };
  }

  return { verified: true, imageBuffer, reason: 'ok' };
}
